services:

  keycloak:
    image: quay.io/keycloak/keycloak:26.2
    command:
      - start-dev
      - --import-realm
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "exec 3<>/dev/tcp/localhost/8080"
        ]
      interval: 5s
      timeout: 3s
      retries: 20
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json

  customer-app:
    build:
      context: ./customer-app

    ports:
      - "8081:8081"

    depends_on:
      keycloak:
        condition: service_healthy

  payment-app:
    build:
      context: ./payment-app

    ports:
      - "8082:8082"

    depends_on:
      keycloak:
        condition: service_healthy